### ISSUE TITLE
Support for multiple outputs

### ISSUE THREAD

**Issue by vedadux** [quentin-meunier/VerifMSI#1]
Dear VerifMSI team,

I have tried out the tool, and it seems to work great for simple gadgets like the ones in the paper!
However, it would be great if the tool supported circuits with multiple shared outputs. 
Namely, for `checkSecurity`, the outputs are provided as a list of arguments, and are assumed to be 
part of the same shared output. This messes with security notions, e.g., PINI properties fail due to wrong share indexes.

It would be great if we could instead provide a list of shared outputs, instead of a list of shares.

Best regards,
Vedad

**Comment by quentin-meunier** [comment]
Hello,

Thank you for your message.
I have added the possibility to pass lists of shares as parameters to the checkSecurity function for the PINI property (the old syntax is still valid). In order to specify that you have 2 outputs u and v on 4 shares, you can do something like:

`nbLeak, nbCheck = checkSecurity(order, withGlitches, prop, [u0, u1, u2, u3], [v0, v1, v2, v3])`

Please let me know if the results you obtain are what you expect or not.

**Comment by vedadux** [comment]
Hey,

I have tried out your fix. The procedure does accept multiple shared outputs now.
**However**, I am afraid it is **NOT CORRECT** anymore. In the PINI definition, the adversary chooses t1 internal probes (inputs, temporaries or even outputs) and t2 output domains, giving them the corresponding shares of each output, such that t1+t2 <= t (the attack order).

For example, inputs a=[a0, a1, a2, a3] and b=[b0, b1, b2, b3] for t=3 as in your example above, an attacker choosing t1=1, with probe set {P} and t2=2 with domains {1,3} would get probes {P, u1, u3, v1, v3}, which need to be simulated using {a1, a3, b1, b3} and either {a0, b0} or {a2, b2}, depending on what is needed for P. I hope that makes sense.
What I feel like is happening in the code is that all probe sets that include <=3 probes are analyzed, but here you would have 5 actually. Either way, I am getting wrong claims of PINI security, as compared to share-wise ANDing together (or concatenating) all outputs, to simulate the above behavior.

I hope that helps.

Best regards,
Vedad

**Comment by quentin-meunier** [comment]
Hello,

Thank you for your reply.

> In the PINI definition, the adversary chooses t1 internal probes (inputs, temporaries or even outputs) and t2 output domains, giving them the corresponding shares of each output

Clearly this is not the definition I used (and indeed in this case only triplets are analyzed). Could you give me a reference of an article defining PINI for a gadget with multiple outputs?

Also,

> and either {a0, b0} or {a2, b2}, depending on what is needed for P

Why could not it be {a0, b2} or {a2, b0}? The PINI definition I used for implementing single output gadgets verification did not specify share indexes between different inputs had to be the same, and this is currently not the case in the tool.

Kind regards.

**Comment by vedadux** [comment]
Hello,

PINI was defined by Cassiers and Standaert in [Trivially and Efficiently Composing Masked Gadgets With Probe Isolating Non-Interference](https://ieeexplore.ieee.org/abstract/document/8979162) and works for arbitrarily many shared inputs and outpus. Here is a quote of the definition:
```
Definition 5 (Probe-Isolating Non-Interference): Let G be a gadget over d shares and P a set of t1 probes on wires of
G (called internal probes). Let A be a set of t2 share indices. G is t-Probe-Isolating Non-Interfering (t-PINI) iff for all P
and A such that t1 + t2 ≤ t, there exists a set B of at most t1 share indices such that probes on the set of wires P ∪ y^{G}_
{A,*} can be simulated with the wires x^{G}_{A∪B,*}.
```

Here, x^{G} are the inputs to the gadget G, and y^{G} are the outputs of gadget G. Moreover, for a vector v of shared signals, the notation v_{S, T}, where S and T are index sets, refers to the shares with indices in S of the vector elements with indices in T. For example, if v consists of 5 signals (a, b, c, d, e) with 4 shares each (a0, a1, a2, a3) etc., then v_{{1,2}, {3, 4}} refers to the set {d1, d2, e1, e2}. They use the shorthand * to refer to all indices, meaning v_{{1, 2}, * } = {a1, a2, b1, b2, c1, c2, d1, d2, e1, e2} and v_{ * , {3,4}} = {d0, d1, d2, d3, e0, e1, e2, e3}.

I hope this clarifies everything a bit.

Edit: Markdown formatting

Best regards

**Comment by quentin-meunier** [comment]
Ok, I should have cafefully read the original definition earlier...

If I am fairly confident in the fact that I can adapt both the tuple enumeration and the ending condition, I think it will require some time before I can have something working (I don't have too much free time at the moment). I will let you know when I am done.

Kind regards.

**Comment by vedadux** [comment]
Thanks, please let me know if/when this is adapted.

As a sidenote, is the PINI check for single outputs correct?
Your earlier comment, regarding {a0, b2} or {a2 ,b0} threw me off there, 
because it kind of implied that e.g. {a1, a3, b1, b3, a0, b2} would be considered 
a valid simulation set in the current implementation. Can you clarify this?
It would help me out a lot to know this.

**Comment by quentin-meunier** [comment]
Yes that's what I meant, {a0, a1, a3, b0, b1, b2} would be considered valid if the tuple contained two shares u0 and u1 of a single output u and an internal probe.

I have implemented the PINI verification but not committed it as I am having troubles to validate/verify the results by lack of well-known PINI/non PINI gadgets. I think the tuple enumeration is good, and the condition for concluding looks ok, but I am less confident in the optimisations aiming at reducing the number of probes. You can send me some gadgets if you want or I can commit the actual version if you want to give it a try (and play with the 'remSingleInputProbes'Opt / 'remRedundantProbesOpt' flags).

Edit: I have committed/pushed the corrected PINI verification. Let me know if you notice anythnig wrong.

**Comment by quentin-meunier** [comment]
Hello Vedadux,

Could you tell me if the changes I made fixed the uncorrect behaviours that you observed?

Thanks!

**Comment by vedadux** [comment]
Hi!

I did not have the time to check it out, since I got sidetracked by other responsibilities/work.
I will let you know when I have something, but I do not expect it to be soon. In the meantime, 
you can close the issue if you want.

Best regards,
Vedad

**Comment by quentin-meunier** [comment]
Hi Vedad,

Ok, no problem, let me know when you have checked, I am closing the issue.

Kind regards,
Quentin
